### ISSUE TITLE
Inline border aren't visible

### ISSUE THREAD

**Issue by Arkezis** [smacinnis-smsoft/devops-free#2]
Hi,

It seems that inline border are not visible in the "Description" view despite they are well visible in the "Advanced description" view.
However, outline borders are visible on both tabs. Changing size, color, etc doesn't help.

thanks,

**Comment by smacinnis-smsoft** [comment]
Can you attach an example using the code viewer?  
adding border-inline and border-inline-style to elements works as expected.
If you are referring to tables, cells and rows only inherit color from adding a table border in table properties context menu.
Rows and cells are bordered using single or multi-select then choosing border styles from their context menu.

**Comment by Arkezis** [comment]
Ok, I didn't see the "context menu" when selecting cells !
It works for row but I don't have the option "column properties"
![Screenshot 2023-10-05 at 09 46 32](https://github.com/smacinnis-smsoft/devops-free/assets/2463222/3332640e-a94f-49be-997d-3e7c968e2d56)
![Screenshot 2023-10-05 at 09 46 38](https://github.com/smacinnis-smsoft/devops-free/assets/2463222/91bae490-af7a-4a04-831e-a7693741c6fd)

**Comment by smacinnis-smsoft** [comment]
There's no parent element in html for column cells, just row.  Multi-select cells vertically and use the context menu to style a group of column cells all at once.
